services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root-pass
      MARIADB_DATABASE: appdb
      MARIADB_USER: appuser
      MARIADB_PASSWORD: app-pass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot-pass"]
      interval: 5s
      timeout: 3s
      retries: 20

  wiremock:
    image: wiremock/wiremock:3.9.1
    container_name: wiremock
    restart: unless-stopped
    ports:
      - "18080:8080"
    volumes:
      - ./docker/wiremock:/home/wiremock
    command: ["--verbose"]

  api-payment-gateway:
    build:
      context: .
      dockerfile: modules/bootstrap/api-payment-gateway/Dockerfile
    container_name: api-payment-gateway
    restart: unless-stopped
    depends_on:
      - mariadb
      - wiremock
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local-docker
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/appdb
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: app-pass
      SPRING_SQL_INIT_MODE: never
      PG_BASE_URL: http://wiremock:8080
      PG_API_KEY: test-api-key

volumes:
  dbdata:
